apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
  namespace: data
spec:
  replicas: 0
  selector:
    matchLabels:
      app: ingest
  template:
    metadata:
      labels:
        app: ingest
    spec:
      containers:
        - name: ingest
          image: undpgeohub.azurecr.io/geohub-data-pipeline:main
          ports:
            - containerPort: 8000
          env:
            - name: AZURE_ACCESS_KEY
              value: "$AZURE_ACCESS_KEY"
            - name: ACCOUNT_NAME
              value: "$ACCOUNT_NAME"
            - name: CREDENTIAL_STRING
              value: "$CREDENTIAL_STRING"
            - name: CONTAINER_NAME
              value: "$CONTAINER_NAME"
            - name: ACCOUNT_URL
              value: "$ACCOUNT_URL"
            - name: CONNECTION_STRING
              value: "$CONNECTION_STRING"
            - name: SERVICE_BUS_CONNECTION_STRING
              value: "$SERVICE_BUS_CONNECTION_STRING"
            - name: SERVICE_BUS_QUEUE_NAME
              value: "$SERVICE_BUS_QUEUE_NAME"
          imagePullPolicy: Always