apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingest-ingress
  namespace: data
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: geohub-data-pipeline.undp.org
    http:
      paths:
      - path: /ingest
        pathType: Prefix
        backend:
          service:
            name: ingest-service
            port:
              name: http
