name: Docker Image Deployment CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  IMAGE_NAME: ${{ github.event.repository.name }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log into ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy ingest to kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f deployment/yaml/ingest-environment.yaml
      - name: Create Secrets
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: create secret generic ingest-secrets --from-literal=AZURE_ACCESS_KEY=${{ secrets.AZURE_ACCESS_KEY }} --from-literal=ACCOUNT_NAME=${{ secrets.ACCOUNT_NAME }} --from-literal=CREDENTIAL_STRING=${{ secrets.CREDENTIAL_STRING }} --from-literal=CONTAINER_NAME=${{ secrets.CONTAINER_NAME }} --from-literal=ACCOUNT_URL=${{ secrets.ACCOUNT_URL }} --from-literal=CONNECTION_STRING=${{ secrets.CONNECTION_STRING }} --from-literal=SERVICE_BUS_CONNECTION_STRING=${{ secrets.SERVICE_BUS_CONNECTION_STRING }} --from-literal=SERVICE_BUS_QUEUE_NAME=${{ secrets.SERVICE_BUS_QUEUE_NAME }} -n ${{ secrets.DEPLOYMENT_NAMESPACE }}
      - name: Rollout new image
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment/${{ secrets.DEPLOYMENT_NAME }} -n ${{ secrets.DEPLOYMENT_NAMESPACE }}
    