# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - geohub-upload-trigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://undpgeohub.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7f2c17ca46994886bd9f4844c9431ca9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1c3a9fc0c98c4d07b8456ac736a347f5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: undpgeohub.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7f2c17ca46994886bd9f4844c9431ca9 }}/geohub-data-pipeline:${{ github.sha }}
        file: ./azure_functions/blob_upload_trigger/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'geohub-upload-trigger'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cb1d3682c9814eb38f73c536e9536ec7 }}
        images: 'undpgeohub.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7f2c17ca46994886bd9f4844c9431ca9 }}/geohub-data-pipeline:${{ github.sha }}'